name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu! ueueueueueueeu"

      - name: Echo the message2
        run: |
          echo "second message"
      - name: Run Path
        run: pwd
      - name: Run Path
        run: ls -ltra
          
